
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-lumesai
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata_lumesai:/var/lib/postgresql/data

volumes:
  pgdata_lumesai:
